[package]
name = "ebb-and-flow"
version = "0.1.0"
edition = "2024"

[features]
timer = []

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
bitvec = { version = "1.0.1", default-features = false, features = ["std"] }
# fixed = "1.29.0"
